# https://github.com/terrastruct/d2
# Update: 2024-03-06

# When outputting SVG, bundle all assets and layers into the output file.
# Type boolean, default: true
bundle: true

# An appendix for tooltips and links is added to PNG exports since they are not interactive.
# Type boolean, default: false
force-appendix: false

# Print debug logs.
# Type boolean, default: false
debug: false

# The layout engine used.
# Type string, default: "dagre"
layout: "dagre"

# The diagram theme ID.
# Type integer, default: 0
theme: 0

# The theme to use when the viewer's browser is in dark mode.
# When setting to -1, theme is used for both light and dark mode.
# This option is not applicable to PNG format in Sublime Text.
# Type integer, default: -1
dark-theme: -1

# Pixels padded around the rendered diagram.
# Type integer, default: 100
pad: 100

# If given, multiple boards are packaged as 1 SVG which transitions through each
# board at the interval (in milliseconds). Can only be used with SVG exports.
# Type integer, default: 0
animate-interval: 0

# The maximum number of seconds that D2 runs for before timing out and exiting.
# Note: Formatter has its own default timeout of 10. Adjust this in settings.
# Type integer, default: 120
timeout: 120

# Render the diagram to look like it was sketched by hand.
# Type boolean, default: false
sketch: false

# Browser executable that watch opens. Setting to 0 opens no browser.
# Type string, default: ""
browser: ""

# Center the SVG in the containing viewbox, such as your browser screen.
# Type boolean, default: false
center: false

# Scale the output. E.g., 0.5 to halve the default size. Default -1 means
# that SVG's will fit to screen and all others will use their default render
# size. Setting to 1 turns off SVG fitting to screen.
# Type float, default: -1
scale: -1

# Target board to render. Pass an empty string to target root board.
# If target ends with "*", it will be rendered with all of its scenarios,
# steps, and layers. Otherwise, only the target board will be rendered.
# E.g. target: "" to render root board only or target: "layers.x.*" to
# render layer "x" with all of its children.
# Type string, default: "*"
target: "*"

# Path to .ttf file to use for the regular font. If none provided,
# Source Sans Pro Regular is used.
# Type string, default: ""
font-regular: ""

# Path to .ttf file to use for the italic font. If none provided,
# Source Sans Pro Regular-Italic is used.
# Type string, default: ""
font-italic: ""

# Path to .ttf file to use for the bold font. If none provided,
# Source Sans Pro Bold is used.
# Type string, default: ""
font-bold: ""

# Path to .ttf file to use for the semibold font. If none provided,
# Source Sans Pro Semibold is used.
# Type string, default: ""
font-semibold: ""
