# $ fourmolu --print-defaults
# Update: 2023-12-08

# Number of spaces per indentation step
indentation: 4

# Max line length for automatic line breaking (choices: none, or any non-negative integer)
column-limit: none

# Styling of arrows in type signatures (choices: trailing, leading, or leading-args)
function-arrows: trailing

# How to place commas in multi-line lists, records, etc. (choices: leading or trailing)
comma-style: leading

# Styling of import/export lists (choices: leading, trailing, or diff-friendly)
import-export-style: diff-friendly

# Whether to full-indent or half-indent 'where' bindings past the preceding body (choices: false, or true)
indent-wheres: false

# Whether to leave a space before an opening record brace (choices: false, or true)
record-brace-space: false

# Number of spaces between top-level declarations
newlines-between-decls: 1

# How to print Haddock comments (choices: single-line, multi-line, or multi-line-compact)
haddock-style: multi-line

# How to print module docstring (choices: single-line, multi-line, or multi-line-compact)
haddock-style-module: multi-line

# Styling of let blocks (choices: auto, inline, newline, or mixed)
let-style: auto

# How to align the 'in' keyword with respect to the 'let' keyword (choices: left-align, right-align, or no-space)
in-style: right-align

# Whether to put parentheses around a single constraint (choices: auto, always, or never)
single-constraint-parens: always

# Output Unicode syntax (choices: detect, always, or never)
unicode: never

# Give the programmer more choice on where to insert blank lines (choices: false, or true)
respectful: true

# Whether to put parentheses around a single deriving class (choices: auto, always, or never)
# Not available in the latest fourmolu 0.14.1.0 at time of writing 2023-12-08.
# single-deriving-parens: always
