#!/bin/sh
# The default /usr/bin/bytecodeviewer script uses bashisms as well as the #!/bin/sh shebang and so it breaks with dash

opts="
  -Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel
  -Dawt.useSystemAAFontSettings=on
  -Dswing.aatext=true
"

exec /usr/bin/java $opts -jar '/usr/share/java/bytecodeviewer/bytecodeviewer.jar' "$@"
