#!/bin/sh

KEYBOARD_PATH="/dev/input/by-path/platform-i8042-serio-0-event-kbd"
MOUSE_PATH="/dev/input/by-path/pci-0000:00:14.0-usb-0:1:1.0-event-mouse"

EVSIEVE_CMD="exec evsieve"

# Check if the keyboard path exists
[ -e "$KEYBOARD_PATH" ] && EVSIEVE_CMD="$EVSIEVE_CMD \\
--input $KEYBOARD_PATH grab \\
--map key:capslock key:esc \\
--map key:rightalt key:rightmeta \\
--output"

# Check if the mouse path exists
[ -e "$MOUSE_PATH" ] && EVSIEVE_CMD="$EVSIEVE_CMD \\
--input $MOUSE_PATH grab \\
--hook btn:middle exec-shell=\"wl-copy -pc; xsel -nc\" \\
--output"

eval "$EVSIEVE_CMD"

