#!/bin/sh
# script for running evsieve
COMMAND="evsieve"

while read -r input; do
    case "$input" in
        *-mouse)
            COMMAND="$COMMAND \\
            --input $input grab \\
            --hook btn:middle exec-shell=\"wl-copy -pc; xsel -nc\" \\
            --output"
            ;;
        *-kbd)
            COMMAND="$COMMAND \\
            --input $input grab \\
            --map key:capslock key:esc \\
            --map key:rightalt key:rightmeta \\
            --output"
            ;;
    esac
done <<EOF
$(find /dev/input/by-path -name \*-event-\* | while read -r symlink; do echo "$(realpath "$symlink") $symlink"; done | awk '!seen[$1]++ { print $2 }')
EOF

eval exec "$COMMAND"

