#!/bin/sh
# launch fuzzel with path executables instead of desktop files as it is by default

COMMAND="$(dmenu_path | fuzzel --dmenu)"
[ $? -ne 0 ] && exit 0 # don't continue if nothing was selected

eval exec env TERMINAL= "$HOME"/scripts/term "$COMMAND"

