#!/bin/sh
# kill all programs when this script is killed
trap 'tmp="$(mktemp)"; jobs -p > "$tmp"; xargs kill < "$tmp"; rm "$tmp"' INT TERM HUP

# start layout manager
#rivertile -view-padding 0 -outer-padding 0 2>&1 &
#rivercarro -inner-gaps 0 -outer-gaps 0 2>&1 &
wideriver \
	--layout left \
	--layout-alt monocle \
	--stack dwindle \
	--count-master 1 \
	--ratio-master 0.5 \
	--count-wide-left 1 \
	--inner-gaps 0 \
	--outer-gaps 0 \
	--smart-gaps \
	--ratio-wide 0.35 \
	--border-color-focused 0x45475A \
	--border-color-focused-monocle 0x45475A \
	--border-color-unfocused 0x313244 \
	--border-width 1 \
	--border-width-monocle 1 \
	--border-width-smart-gaps 0 \
	--log-threshold info \
	2>&1 &

# set layout manager
riverctl default-layout wideriver

wait

