#!/bin/sh

# https://github.com/sudo-project/sudo/blob/de3b179a03b91fe17ffda720cd097745140d4c5b/plugins/sudoers/check.c#L286-L291
cat << EOF

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

For security reasons, the password you type will not be visible.

EOF

. "$(dirname "$0")"/../unwrap.sh

# https://codeberg.org/TotallyLeGIT/doasedit/src/commit/5bf964e4a3634db897fdbbd7a52319a95157d8c2/doasedit#L188-L195
for tries in 2 1 0; do
  if "$(basename "$0")" "$@"; then break
  elif [ "$tries" -eq 0 ]; then
    echo doas wrapper: 3 incorrect password attempts
    exit 1
  fi
done

