#!/usr/bin/env bash

# https://gist.github.com/memchr/a40f9fdb95f9e263fc7a3f6a784b3feb
# https://github.com/hyprwm/Hyprland/issues/3134

set -e

[ -n $HYPRLAND_DEBUG_CONF ] && exit 0

_envs=(
	DBUS_SESSION_BUS_ADDRESS
	XAUTHORITY
	# display
	WAYLAND_DISPLAY
	DISPLAY
	# xdg
	USERNAME
	XDG_BACKEND
	XDG_CURRENT_DESKTOP
	XDG_SESSION_TYPE
	XDG_SESSION_ID
	XDG_SESSION_CLASS
	XDG_SESSION_DESKTOP
	XDG_SEAT
	XDG_VTNR
	# hyprland
	HYPRLAND_CMD
	HYPRLAND_INSTANCE_SIGNATURE
	# sway
	SWAYSOCK
	# misc
	XCURSOR_SIZE
	# toolkit
	_JAVA_AWT_WM_NONREPARENTING
	QT_QPA_PLATFORM
	QT_WAYLAND_DISABLE_WINDOWDECORATION
	GRIM_DEFAULT_DIR
	# ssh
	SSH_AUTH_SOCK
)

# Import to systemd and dbus user session
dbus-update-activation-environment --systemd "${_envs[@]}"

# Import to tmux server
for v in "${_envs[@]}"; do
	if [[ -n ${!v} ]]; then
		tmux setenv -g "$v" "${!v}"
	fi
done

