#!/bin/sh
# kill other instances of calling script
# source this script in other scripts to kill other instances

# https://stackoverflow.com/questions/38435772/bash-script-kill-all-same-processes-instead-of-this-one
kill $(pgrep -x "$(basename "$0")" | grep -v ^$$$) > /dev/null 2>&1

. ~/scripts/unwrap
exec "$(basename "$0")" "$@"

