#!/bin/sh
# Toggles touchpad whether mouse is connected/disconnected.
# Made redundant by libinput's Send Events Mode set to "disabled on external mouse", but hyprland and plasma don't support this libinput option

# check if mouse is connected
MOUSEEXISTS=0
for MOUSE in $(find /sys/class/input -name mouse\*); do
    # exclude devices that aren't physically connected mice
    grep -iq -E "touchpad|elan|virtual|kanata" "$MOUSE"/device/name && continue
    MOUSEEXISTS=1
    break
done

# find touchpad
for INPUT in $(find /sys/class/input -name input\*); do
    grep -iq -E "touchpad" "$INPUT"/name || continue
    TOUCHPAD=$INPUT
    break
done

# set inhibited setting
echo "$MOUSEEXISTS" > "$TOUCHPAD"/inhibited

# loop through each hyprland instance
#for i in $(hyprctl instances -j | jq ".[].instance" -r); do
    #export HYPRLAND_INSTANCE_SIGNATURE=$i

    # enable/disable the touchpad
    #TOUCHPAD="$(hyprctl devices -j | jq -r '.mice[] | select(.name | contains("touchpad")) | .name')"
    #hyprctl -r -- keyword "device["$TOUCHPAD"]:enabled" "$ENABLED"
#done

