#!/bin/sh
# Note: $TERMINAL is exported in .zshenv

if [ "$#" -lt 1 ]; then
  echo "Usage: $0 <command> [args...]"
  exit 1
fi

# get terminal as an argument
#TERMINAL=$1
#shift

# hold (wait for return)
#COMMAND="${SHELL:-"/bin/sh"} -ic '$@; read'"

# hold (wait for any key)
# https://stackoverflow.com/questions/43030991/korn-shell-how-can-i-make-press-any-key-to-continue
# https://www.unix.com/unix-for-dummies-questions-and-answers/3197-making-sh-wait-user-input.html?s=3af7d25036436ca99b7d2204da6528fe
COMMAND="${SHELL:-"/bin/sh"} -ic '\
  $@; \
  tput smso; \
  echo \"Press any key to return\c\"; \
  tput rmso; \
  oldstty=\$(stty -g); \
  stty -icanon -echo min 1 time 0; \
  dd bs=1 count=1 >/dev/null 2>&1; \
  stty "\$oldstty" \
'"

# enter interactive shell
#COMMAND="${SHELL:-"/bin/sh"} -ic '$@; ${SHELL:-"/bin/sh"} -i'" 

case "$TERMINAL" in
  xterm|alacritty)
    eval exec "$TERMINAL" -e "$COMMAND";;
  foot|kitty)
    eval exec "$TERMINAL" -- "$COMMAND";;
  wezterm)
    eval exec "$TERMINAL" start -- "$COMMAND";;

  *)
    echo Unsupported terminal: "$TERMINAL"
    exit 1;;
esac

