#!/bin/sh -i
# Note: $TERMINAL is exported in .zshenv

if [ "$#" -lt 1 ]; then
  echo "Usage: $0 <command> [args...]"
  exit 1
fi

# get terminal as an argument
#TERMINAL=$1
#shift

# 1 -> hold (wait for return)
# 2 -> hold (wait for any key): https://www.unix.com/unix-for-dummies-questions-and-answers/3197-making-sh-wait-user-input.html?s=3af7d25036436ca99b7d2204da6528fe
# 3 -> enter interactive shell
# anything else -> nothing
COMMAND="${SHELL:-"/bin/sh"} -ic '\
  $@; \
  case \"\$USEHOLDMODE\" in \
    1) read ;; \
    2) \
      tput smso; \
      echo \"Press any key to return\c\"; \
      tput rmso; \
      oldstty=\$(stty -g); \
      stty -icanon -echo min 1 time 0; \
      dd bs=1 count=1 >/dev/null 2>&1; \
      stty \"\$oldstty\" ;; \
    3) ${SHELL:-"/bin/sh"} -i ;; \
  esac \
'"

case "$TERMINAL" in
  "")
    eval exec "$COMMAND";;
  xterm|alacritty)
    eval exec "$TERMINAL" -e "$COMMAND";;
  foot|kitty)
    eval exec "$TERMINAL" -- "$COMMAND";;
  wezterm)
    eval exec "$TERMINAL" start -- "$COMMAND";;

  *)
    echo Unsupported terminal: "$TERMINAL"
    exit 1;;
esac

